### ISSUE TITLE
Keine Objekterkennung - Fehlersuche

### ISSUE THREAD

**Issue by Uorgh** [wiegehtki/zoneminder#6]
Leider funktioniert bei mir die Objekterkennung nicht wie im Video beschrieben.

Folgende Fehlermeldung erhalte ich:
`sudo -u www-data /var/lib/zmeventnotification/bin/zm_detect.py --config /etc/zm/objectconfig.ini  --eventid 130 --monitorid 130 --debug
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 15, in <module>
    import imutils
  File "/usr/local/lib/python3.6/dist-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/usr/local/lib/python3.6/dist-packages/imutils/convenience.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
`
Wie kann ich den Fehler denn weiter eingrenzen?

**Comment by Uorgh** [comment]
Ähnliches bei start der training_gesichter.sh:

07/22/22 15:59:22 zm_train_faces[2474] INF ZMLog.py:292 [Setting up signal handler for logs]

07/22/22 15:59:22 zm_train_faces[2474] INF ZMLog.py:301 [Switching global logger to ZMLog]

Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_train_faces.py", line 12, in <module>
    import pyzm.ml.face_train_dlib as train
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/face_train_dlib.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Uorgh** [comment]
Quelle: https://stackoverflow.com/questions/19876079/cannot-find-module-cv2-when-using-opencv
Ausgeführt: pip install opencv-python

Collecting opencv-python
  Downloading opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
     |████████████████████████████████| 60.9 MB 93 kB/s
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from opencv-python) (1.19.5)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.6.0.66
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv


Jetzt erhalte ich von training_gesichter.sh bereits folgende Ausgabe:

07/22/22 16:10:37 zm_train_faces[2679] INF ZMLog.py:292 [Setting up signal handler for logs]

07/22/22 16:10:37 zm_train_faces[2679] INF ZMLog.py:301 [Switching global logger to ZMLog]

07/22/22 16:10:44 zm_train_faces[2679] INF utils.py:405 [Reading config from: /etc/zm/objectconfig.ini]

07/22/22 16:10:44 zm_train_faces[2679] INF utils.py:410 [Reading secrets from: /etc/zm/secrets.ini]

07/22/22 16:10:44 zm_train_faces[2679] INF utils.py:511 [Ignoring monitor specific settings, as you did not provide a monitor id]

07/22/22 16:10:44 zm_train_faces[2679] ERR face_train_dlib.py:128 [Error initializing face recognition: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in file /tmp/pip-install-1jgz4ilm/dlib_2474e16c4ce443b992647685bf39a35e/dlib/cuda/cuda_utils.h:164. code: 98, reason: invalid device function]

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/face_train_dlib.py", line 84, in train
    number_of_times_to_upsample=upsample_times)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 119, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 103, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in file /tmp/pip-install-1jgz4ilm/dlib_2474e16c4ce443b992647685bf39a35e/dlib/cuda/cuda_utils.h:164. code: 98, reason: invalid device function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_train_faces.py", line 33, in <module>
    train.FaceTrain(options=g.config).train(size=args['size'])
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/face_train_dlib.py", line 130, in train
    'Error opening known faces directory. Is the path correct?')
ValueError: Error opening known faces directory. Is the path correct?

**Comment by Uorgh** [comment]
Nachdem ich jetzt die kompletten Scripte nochmal manuell durchlaufen habe (siehe entsprechende Fehlermeldungen als Issues) habe ich aktuell diese Fehlermeldung beim Aufruf von training_gesichter.sh:
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_train_faces.py", line 4, in <module>
    import pyzm.ZMLog as log
ModuleNotFoundError: No module named 'pyzm'

... und beim aufruf von zm_detect.py: 
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 26, in <module>
    import pyzm.ZMLog as log
ModuleNotFoundError: No module named 'pyzm'

**Comment by Uorgh** [comment]
Unter 20.04 folgende Fehlermeldung von training_gesichter.sh:

07/24/22 15:51:25 zm_train_faces[1779] INF ZMLog.py:292 [Setting up signal handler for logs]

07/24/22 15:51:25 zm_train_faces[1779] INF ZMLog.py:301 [Switching global logger to ZMLog]

/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_train_faces.py", line 12, in <module>
    import pyzm.ml.face_train_dlib as train
  File "/usr/local/lib/python3.8/dist-packages/pyzm/ml/face_train_dlib.py", line 18, in <module>
    import face_recognition
  File "/usr/local/lib/python3.8/dist-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/local/lib/python3.8/dist-packages/face_recognition/api.py", line 26, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-pjtx2cxt/dlib_ef9118d08f1747c6a4d08a1baa3b1ae6/dlib/cuda/gpu_data.cpp:204. code: 804, reason: forward compatibility was attempted on non supported HW
