### ISSUE TITLE
Final.sh: Fehler in Install.sh von zmeventnotification

### ISSUE THREAD

**Issue by Uorgh** [wiegehtki/zoneminder#9]
Am Ende erhalte ich folgende Meldungen:
Cleaning up...
  Removing source in /tmp/pip-px3b6uon-build
  Removing source in /tmp/pip-build-aaahv99i/Pillow
  Removing source in /tmp/pip-build-aaahv99i/Shapely
  Removing source in /tmp/pip-build-aaahv99i/imageio-ffmpeg
  Removing source in /tmp/pip-build-aaahv99i/pygifsicle
  Removing source in /tmp/pip-build-aaahv99i/pyzm
  Removing source in /tmp/pip-build-aaahv99i/psutil
protobuf requires Python '>=3.7' but the running Python is 3.6.9
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/usr/lib/python3/dist-packages/pip/utils/packaging.py", line 57, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pip.exceptions.UnsupportedPythonVersion: protobuf requires Python '>=3.7' but the running Python is 3.6.9
ERROR:python hooks setup failed
Installing package deps...
Installing gifsicle, if needed...
Vormals nicht ausgewähltes Paket gifsicle wird gewählt.
(Lese Datenbank ... 126432 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../gifsicle_1.91-2_amd64.deb ...
Entpacken von gifsicle (1.91-2) ...
gifsicle (1.91-2) wird eingerichtet ...
Trigger für man-db (2.8.3-2ubuntu0.1) werden verarbeitet ...

Skipping Hook config install

Creating a migrated objectconfig if required
Current version of file is 1.2
Nothing to migrate

*** Please remember to start the Event Server after this update ***

Ich werde später noch versuchen, ob dies durch die Installation einer anderen Python-Version gelöst wird...

**Comment by Uorgh** [comment]
Laut [dieser](https://zmeventnotification.readthedocs.io/en/latest/guides/install.html) Seite soll man die Installation mit diesem Befehl prüfen:
sudo -u www-data /usr/bin/zmeventnotification.pl --debug

Dies scheint bei mir wohl trotz dieses obigen Fehlers zu funktionieren:
23.07.2022 22:52:47.381401 zmeventnotification[25806].INF [main:338] [Running on WebSocket library version:0.004]
INF:2022-07-23,22:52:47 PARENT: using config file: /etc/zm/zmeventnotification.ini
23.07.2022 22:52:47.481234 zmeventnotification[25806].INF [main:1048] [PARENT: using config file: /etc/zm/zmeventnotification.ini]
INF:2022-07-23,22:52:47 PARENT: using secrets file: /etc/zm/secrets.ini
23.07.2022 22:52:47.538733 zmeventnotification[25806].INF [main:1048] [PARENT: using secrets file: /etc/zm/secrets.ini]
DBG-2:2022-07-23,22:52:47 PARENT: Got secret token !ZMES_PICTURE_URL
DBG-2:2022-07-23,22:52:47 PARENT: Got secret token !ZM_USER
DBG-2:2022-07-23,22:52:47 PARENT: Got secret token !ZM_PASSWORD
DBG-2:2022-07-23,22:52:47 PARENT: config string substitution: {{base_data_path}} is '/var/lib/zmeventnotification'

Configuration (read /etc/zm/zmeventnotification.ini):

Secrets file.......................... /etc/zm/secrets.ini
Base data path........................ /var/lib/zmeventnotification
Restart interval (secs)............... 0

Use admin interface .................. no
Admin interface password.............. (undefined)
Admin interface persistence file ..... /var/lib/zmeventnotification/misc/escontrol_interface.dat

Port ................................. 9000
Address .............................. [::]
Event check interval ................. 5
Monitor reload interval .............. 300
Skipped monitors...................... (undefined)

Auth enabled ......................... yes
Auth timeout ......................... 20

Use API Push.......................... no
API Push Script....................... (undefined)

Use FCM .............................. yes
Use FCM V1 APIs....................... yes
FCM Date Format....................... %I:%M %p, %d-%b
Only show latest FCMv1 message........ no
Android FCM push priority............. high
Android FCM push ttl.................. (undefined)
Log FCM message ID.................... NONE
Log RAW FCM Messages...................no
FCM V1 URL............................ https://us-central1-ninja-1105.cloudfunctions.net/send_push
FCM V1 Key.............................default

Token file ........................... /var/lib/zmeventnotification/push/tokens.txt

Use MQTT ............................. no
MQTT Server .......................... 127.0.0.1
MQTT Topic ........................... zoneminder
MQTT Username ........................ (undefined)
MQTT Password ........................ (undefined)
MQTT Retain .......................... no
MQTT Tick Interval ................... 15
MQTT TLS CA ........................ (undefined)
MQTT TLS Cert ........................ (undefined)
MQTT TLS Key ........................ (undefined)
MQTT TLS Insecure ........................ no

SSL enabled .......................... yes
SSL cert file ........................ /etc/apache2/ssl/cert.crt
SSL key file ......................... /etc/apache2/ssl/cert.key

Verbose .............................. yes
ES Debug level.........................4
Read alarm cause ..................... yes
Tag alarm event id ................... yes
Use custom notification sound ........ no
Send event start notification..........yes
Send event end notification............yes
Monitor rules JSON file................(undefined)

Use Hooks............................. yes
Max Parallel Hooks.................... 0
Hook Script on Event Start ........... '/var/lib/zmeventnotification/bin/zm_event_start.sh'
User Script on Event Start.............(undefined)
Hook Script on Event End.............. (undefined)
User Script on Event End...............(undefined)
Hook Skipped monitors................. (undefined)

Notify on Event Start (hook success).. all
Notify on Event Start (hook fail)..... none
Notify on Event End (hook success).... fcm,web,api
Notify on Event End (hook fail)....... none
Notify End only if Start success...... yes

Use Hook Description.................. yes
Keep frame match type................. yes
Store Frame in ZM......................yes

Picture URL .......................... https://10.123.10.2/zm/index.php?view=image&eid=EVENTID&fid=objdetect&width=600
Include picture....................... yes
Picture username ..................... user
Picture password ..................... (defined)

INF:2022-07-23,22:52:47 PARENT: Push enabled via FCM
23.07.2022 22:52:47.693990 zmeventnotification[25806].INF [main:1048] [PARENT: Push enabled via FCM]
DBG-2:2022-07-23,22:52:47 PARENT: fcmv1: --> FCM V1 APIs: 1
INF:2022-07-23,22:52:47 PARENT: MQTT Disabled
23.07.2022 22:52:47.722438 zmeventnotification[25806].INF [main:1048] [PARENT: MQTT Disabled]
INF:2022-07-23,22:52:47 PARENT: |------- Starting ES version: 6.1.28 ---------|
23.07.2022 22:52:47.788924 zmeventnotification[25806].INF [main:1048] [PARENT: |------- Starting ES version: 6.1.28 ---------|]
DBG-2:2022-07-23,22:52:47 PARENT: Started with: perl:/usr/bin/perl and command:/usr/bin/zmeventnotification.pl
Can't ignore signal CHLD, forcing to default.
DBG-1:2022-07-23,22:52:47 PARENT: ES invoked manually. Will handle restarts ourselves
DBG-2:2022-07-23,22:52:47 PARENT: Parent<--Child pipe ready
INF:2022-07-23,22:52:47 PARENT: Event Notification daemon v 6.1.28 starting

23.07.2022 22:52:47.992941 zmeventnotification[25806].INF [main:1048] [PARENT: Event Notification daemon v 6.1.28 starting]
DBG-1:2022-07-23,22:52:48 PARENT: Initializing FCM tokens...
DBG-1:2022-07-23,22:52:48 PARENT: Creating /var/lib/zmeventnotification/push/tokens.txt
DBG-1:2022-07-23,22:52:48 PARENT: Total event client connections: 0

INF:2022-07-23,22:52:48 PARENT: Re-loading monitors
23.07.2022 22:52:48.022534 zmeventnotification[25806].INF [main:1048] [PARENT: Re-loading monitors]
DBG-2:2022-07-23,22:52:48 PARENT: ESCONTROL_INTERFACE is disabled. Not saving control data
DBG-2:2022-07-23,22:52:48 PARENT: checkEvents() new events found=0
DBG-2:2022-07-23,22:52:48 PARENT: About to start listening to socket
INF:2022-07-23,22:52:48 PARENT: Secure WS(WSS) is enabled...
23.07.2022 22:52:48.084034 zmeventnotification[25806].INF [main:1048] [PARENT: Secure WS(WSS) is enabled...]
INF:2022-07-23,22:52:48 PARENT: Web Socket Event Server listening on port 9000
23.07.2022 22:52:48.121492 zmeventnotification[25806].INF [main:1048] [PARENT: Web Socket Event Server listening on port 9000]
DBG-2:2022-07-23,22:52:53 PARENT: ----------> Tick START (active forks:0, total forks:0, active hooks: 0 running for:1 min)<--------------
DBG-2:2022-07-23,22:52:53 PARENT: After tick: TOTAL: 0,  ES_CONTROL: 0, FCM+WEB: 0, FCM: 0, WEB: 0, MQTT:0, invalid WEB: 0, PENDING: 0
DBG-2:2022-07-23,22:52:53 PARENT: There are 0 active child forks & 0 zm_detect processes running...
DBG-2:2022-07-23,22:52:53 PARENT: checkEvents() new events found=0
DBG-2:2022-07-23,22:52:53 PARENT: There are 0 new Events to process
DBG-2:2022-07-23,22:52:53 PARENT: ---------->Tick END (active forks:0, total forks:0, active hooks: 0)<--------------
DBG-2:2022-07-23,22:52:58 PARENT: ----------> Tick START (active forks:0, total forks:0, active hooks: 0 running for:1 min)<--------------
DBG-2:2022-07-23,22:52:58 PARENT: After tick: TOTAL: 0,  ES_CONTROL: 0, FCM+WEB: 0, FCM: 0, WEB: 0, MQTT:0, invalid WEB: 0, PENDING: 0
DBG-2:2022-07-23,22:52:58 PARENT: There are 0 active child forks & 0 zm_detect processes running...
DBG-2:2022-07-23,22:52:58 PARENT: checkEvents() new events found=0
DBG-2:2022-07-23,22:52:58 PARENT: There are 0 new Events to process
DBG-2:2022-07-23,22:52:58 PARENT: ---------->Tick END (active forks:0, total forks:0, active hooks: 0)<--------------
DBG-2:2022-07-23,22:53:03 PARENT: ----------> Tick START (active forks:0, total forks:0, active hooks: 0 running for:1 min)<--------------
DBG-2:2022-07-23,22:53:03 PARENT: After tick: TOTAL: 0,  ES_CONTROL: 0, FCM+WEB: 0, FCM: 0, WEB: 0, MQTT:0, invalid WEB: 0, PENDING: 0
DBG-2:2022-07-23,22:53:03 PARENT: There are 0 active child forks & 0 zm_detect processes running...
DBG-2:2022-07-23,22:53:03 PARENT: checkEvents() new events found=0
DBG-2:2022-07-23,22:53:03 PARENT: There are 0 new Events to process
... usw

**Comment by Uorgh** [comment]
Unter 20.04 scheint es besser zu laufen. da hab ich zwischendrin nur folgendes gefunden:

Traceback (most recent call last):
  File "./hook/zm_detect.py", line 13, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

und:

  /usr/lib/python3/dist-packages/setuptools/dist.py:481: UserWarning: The version specified ('') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    warnings.warn(
